# Generated by Django 4.2.15 on 2024-09-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='sudoku_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SudokuBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('grayscale_data', models.JSONField(blank=True, default=dict, null=True)),
                ('contours', models.TextField(blank=True, null=True)),
                ('warp_data', models.JSONField(blank=True, default=dict, null=True)),
                ('contrasted_data', models.JSONField(blank=True, default=dict, null=True)),
                ('sudoku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sudoku')),
            ],
        ),
        migrations.CreateModel(
            name='BoardCell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('predicted_value', models.CharField(blank=True, max_length=1, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sudokuboard')),
            ],
        ),
    ]
