# Generated by Django 4.2 on 2024-06-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sudoku',
            new_name='Image',
        ),
    ]
