# Generated by Django 4.2.15 on 2024-09-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokuboard',
            name='original_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
