# Generated by Django 4.2.15 on 2024-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcell',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardcell',
            name='predicted_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
