# Generated by Django 4.2.15 on 2024-09-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sudokuboard_original_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sudokuboard',
            old_name='original_data',
            new_name='data',
        ),
    ]
