# Generated by Django 4.2.16 on 2024-09-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_boardcell_value_alter_boardcell_predicted_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardcell',
            old_name='value',
            new_name='solved_value',
        ),
    ]
