# Generated by Django 4.2 on 2024-06-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sudoku_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
