# Generated by Django 4.2.15 on 2024-09-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_original_data_sudokuboard_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sudokuboard',
            old_name='countour_data',
            new_name='contour_data',
        ),
    ]
