# Generated by Django 4.2.15 on 2024-09-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_countour_data_sudokuboard_contour_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sudokuboard',
            old_name='contour_data',
            new_name='contours',
        ),
    ]
