# Generated by Django 4.2 on 2024-06-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_image_id_alter_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
