# Generated by Django 4.2.15 on 2024-09-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_contour_data_sudokuboard_contours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokuboard',
            name='contours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
