# Generated by Django 4.2 on 2024-07-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Sudoku',
        ),
    ]
