# Generated by Django 4.2.15 on 2024-09-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sudokuboard_contours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sudokuboard',
            old_name='reshaped_data',
            new_name='warp_data',
        ),
    ]
