# Generated by Django 4.2 on 2024-07-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_image_sudoku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel_size', models.IntegerField(default=7)),
                ('sigma', models.FloatField(default=0.2)),
            ],
        ),
        migrations.CreateModel(
            name='Thresholding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel_size', models.IntegerField(default=11)),
                ('c_const', models.FloatField(default=2.0)),
            ],
        ),
        migrations.AddField(
            model_name='sudoku',
            name='blur_params',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.blurring'),
        ),
        migrations.AddField(
            model_name='sudoku',
            name='threshold_params',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thresholding'),
        ),
    ]
