# Generated by Django 4.2.15 on 2024-09-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_processedimage_sudoku_reshaped_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('data', models.JSONField(default=dict)),
                ('predicted_value', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sudoku',
            name='reshaped_image',
        ),
        migrations.CreateModel(
            name='SudokuBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cells', models.ManyToManyField(to='app.boardcell')),
            ],
        ),
        migrations.AddField(
            model_name='sudoku',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sudokuboard'),
        ),
    ]
