# Generated by Django 4.2.15 on 2024-09-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_boardcell_remove_sudoku_reshaped_image_sudokuboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokuboard',
            name='contrasted_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sudokuboard',
            name='countour_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sudokuboard',
            name='grayscale_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='sudokuboard',
            name='reshaped_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
